## Where are we now
1. Python - general problem solving
2. Data Science - NumPy, Pandas, Sklearn, Matplotlib 
3. ML from Scratch - Intuition (so for those who want to further advance....)
4. Signal Processing - Energy, Telecommunciations, Biosignals, Time Series
5. Deep Learning - PyTorch
   1. One of the most popular DL framework (against TensorFlow)

## Deep Learning vs. Machine Learning

Good News
- Deep Learning can automatically feature engineer / feature selection
- Deep Learning can benefit from huge amount of data, while Machine Learning cannot
  - 100 samples vs 1000 samples, ML will get the same accuracy
  - But DL will see increased accuracy
- Deep Learning is basically stacking a lot of linear regression together
  - DL can learn very complex patterns
  - DL is perfect for (1) images, (2) text, (3) signal (very random)

Bad News
- Deep Learning sucks with small data (vs. Machine Learning) - 5000++ samples
- For Tabular Data, Deep Learning will ALMOST ALWAYS LOSE TO gradient boosting (or its variants)
  - Gradient Boosting is basically decision trees stacking after one another....
  - For most competition, XGBoost and LightGBM are always the winners for tabular data
  - If you work in a company, mostly they use tabular data, then you should look for gradient boosting types.... 
- Deep Learning has NO feature importance; so it's mostly blackbox....(Explanable AI)

# PyTorch

In [1]:
import torch #pip install torch or pip3 install torch or conda install torch
import numpy as np

In [2]:
np.__version__

'1.22.0'

In [3]:
torch.__version__

'1.12.1'

## Torch Tensors

PyTorch don't use NumPy.  Instead, it has its own data structures, called `Tensor`, which support automatic differentiation.

### Create torch tensors from NumPy

In [4]:
#create a numpy array of 1 to 5
arr = np.arange(1, 6)
# arr

#print the data type
arr.dtype  #int64

#print the type()
type(arr)  #belongs to Python itself

numpy.ndarray

In [5]:
#convert numpy to tensor

#1. from_numpy (copy)
torch_arr_from = torch.from_numpy(arr)
torch_arr_from.dtype  #torch.int64
type(torch_arr_from)  #torch.Tensor
torch_arr_from.type() #torch.LongTensor (int64); if torch.IntTensor (int32)
                      #torch.FloatTensor (float32); if torch.DoubleTensor (float64)
#from_numpy is a copy!!!  This is intended, for easy use between numpy and tensor...
# arr[2] = 999
# torch_arr_from

#2. tensor (not a copy)
torch_arr_tensor = torch.tensor(arr)  #everything is the same, except it's NOT a copy
arr[2] = 9999999
torch_arr_tensor

#In our class, mostly we use torch.tensor; it won't fail us :-)


tensor([1, 2, 3, 4, 5])

## Some API to create tensor

- `torch.empty(size)` - any arbitrary numbers
- `torch.ones(size)`
- `torch.zeros(size)`
- `torch.arange(start, stop(ex), step)`
- `torch.linspace(start, stop, how many)`
- `torch.logspace(start, stop, how many)`  - power of 10
    - `torch.rand(size)` - [0, 1)
    - `torch.randn(size)` - std = 1 with uniform distribution
    - `torch.randint(low, high, size)` - [low, high)

In [13]:
#import some deep learning layer
#you have to help me create the right shape to insert to this layer

import torch.nn as nn  #nn contains a lot of useful deep learning layers

linear_layer = nn.Linear(5, 1)  #basically you insert 5 features, output 1 number
linear_layer.weight.shape

#can you guys help me generate any pytorch tensor of size (?, ?)
data = torch.ones((12,5))
output = linear_layer(data)
print(output)

tensor([[0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009],
        [0.8009]], grad_fn=<AddmmBackward0>)


In [22]:
hidden_linear_layer = nn.Linear(100,5)
output_linear_layer = nn.Linear(5,1)
# all_layer = nn.Linear((100,5),1)
# hidden_linear_layer.weight.shape, output_linear_layer.weight.shape
data = torch.ones((1,100))
output = output_linear_layer(hidden_linear_layer(data))
print(output)

model = nn.Sequential(hidden_linear_layer,output_linear_layer)
print(model(data))

tensor([[-0.1794]], grad_fn=<AddmmBackward0>)
tensor([[-0.1794]], grad_fn=<AddmmBackward0>)


tensor([[0.5881]], grad_fn=<AddmmBackward0>)


In [24]:
x = torch.arange(1,6)
print(x.dtype)

torch.int64


In [27]:
x = x.type(torch.float16)
print(x.dtype)

torch.float16


In [33]:
x = torch.arange(10)
y = x.view(2,5)
y[0,0] = 999

In [32]:
x # x,y share memory

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [34]:
y.is_contiguous()


True

In [35]:
z = x.reshape(2,5)
z.is_contiguous()

True

In [38]:
z_t = z.transpose(1,0) # order by index

In [39]:
z_t.is_contiguous()

False

Gradient